kumuluzee:
  name: delivery-server
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/DeliveryDS
      connection-url: jdbc:postgresql://localhost:5432/delivery
      username: postgres
      password: postgres
      pool:
        max-size: 2
  persistence-units:
    - name: "team-globaloptima-delivery-person"
      continue-on-error: false