kumuluzee:
  name: delivery-server
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/DeliveryDS
      connection-url: jdbc:postgresql://localhost:5433/delivery
      username: postgres
      password: postgres
      pool:
        max-size: 2
  health:
    servlet:
      mapping: /health
      enabled: true
    logs:
      enabled: true
      level: INFO
      period-s: 60
    checks:
      disk-space-health-check:
        threshold: 100000000
      data-source-health-checks:
        - jndi-name: jdbc/DeliveryDS
        - type: liveness
      http-health-check:
        - connection-url: https://trueway-matrix.p.rapidapi.com
  persistence-units:
    - name: "team-globaloptima-delivery-person"
      continue-on-error: false
  openapi-mp:
    enabled: true
    scan:
      packages: team.globaloptima
    servlet:
      mapping: /openapi
    servers: https://example-api.com
    ui:
      server-auto-config:
        enabled: true
        original-uri-check: true
      enabled: true
      mapping: /openapi/ui
    scanning:
      debug: true
  metrics:
    servlet:
      enabled: true
      mapping: /metrics
    web-instrumentation:
      - name: metricsEndpoint
        url-pattern: /metrics/*
